### ISSUE TITLE
cp: cannot stat ‘.env.pentaho.sample’: No such file or directory

### ISSUE THREAD

**Issue by joemcl** [eeeschwartz/erikschwartz#4]
Thanks so much for the tutorial by the way. Been stepping through it and hit this bump. Will look at the relevant repo for any update.

**Comment by eeeschwartz** [comment]
Is this in referrence to [an old Pentaho post](https://github.com/eeeschwartz/erikschwartz/commit/03d22646b08fff8a70b77aef125a5bd21997af15)?

If so, here are [newer Pentaho installation instructions](https://github.com/lfucg/lexington-pentaho-etl).

**Comment by eeeschwartz** [comment]
@joemcl Sorry - totally missed your comment. Glad the post was useful! Feel free to send over any other questions/issues.

**Comment by joemcl** [comment]
Thanks, I was looking at 
https://github.com/eeeschwartz/erikschwartz/blob/master/_posts/2014-09-01-install-pentaho-kettle-on-ubuntu-12.04.md
will check out the newer post.
Thanks again!
